"""Audited candidate construction and the frozen candidate pool.

Candidates are generated by the frozen collection policy C0 (normally the
task-capable seed model SEED), audited against the caption contract, paired
by the confound-aware sampler, and frozen before any annotation begins.
After the freeze, candidate text, ids, pair mappings, source checkpoints,
decoding configurations, and audit versions are immutable;
any change requires a new dataset version and a new collection round.
"""
